ShowcaseScreen:
	name: '2.Drug'

    BoxLayout:
		size_hint_y: None
		height: '48dp'
		Label:
			text: 'Acetylsalicylsyra Treo'

		Slider:
			id: s1
			step: 0.5
			min: 0
			max: 5
			on_value: root.slidervalue(s1.value)

		Label:
			text: '{}'.format(s1.value)

    BoxLayout:
		size_hint_y: None
		height: '48dp'
		Label:
			text: 'Paracetamol'

		Slider:
			id: s2
			step: 0.5
			min: 0
			max: 10
			on_value: root.slidervalue(s2.value)

		Label:
			text: '{}'.format(s2.value)
	BoxLayout:
		size_hint_y: None
		height: '48dp'
		Label:
			text: 'Ibuprofen'

		Slider:
			id: s3
			step: 0.5
			min: 0
			max: 10
			on_value: root.slidervalue(s3.value)

		Label:
			text: '{}'.format(s3.value)

	BoxLayout:
		size_hint_y: None
		height: '48dp'
		Label:
			text: 'Diklofenak'

		Slider:
			id: s4
			step: 0.5
			min: 0
			max: 10
			on_value: root.slidervalue(s4.value)

		Label:
			text: '{}'.format(s4.value)
	BoxLayout:
		size_hint_y: None
		height: '48dp'
		Label:
			text: 'Naproxen'

		Slider:
			id: s5
			step: 0.5
			min: 0
			max: 10
			on_value: root.slidervalue(s5.value)

		Label:
			text: '{}'.format(s5.value)
    BoxLayout:
		size_hint_y: None
		height: '48dp'
		Label:
			text: 'Morphine'

		Slider:
			id: s6
			step: 0.5
			min: 0
			max: 10
			on_value: root.slidervalue(s6.value)

		Label:
			text: '{}'.format(s6.value)
	BoxLayout:
		size_hint_y: None
		height: '48dp'
		Label:
			text: 'Tramadol'

		Slider:
			id: s7
			step: 0.5
			min: 0
			max: 10
			on_value: root.slidervalue(s7.value)

		Label:
			text: '{}'.format(s7.value)

