#ShowcaseScreen:
#	name: '8.Graph'

#	TabbedPanel:
#	    id: tab_panel
#	    do_default_tab: False

#	    TabbedPanelItem:
#	        id: tab_graph
#           text: 'Graph'
#          ShowcaseScreen:
#            #on_press: root.one()



<CMplGraph>:
    id: my_graph
    orientation: 'vertical'

TabbedPanel:
    id: tab_panel
    do_default_tab: False

    TabbedPanelItem:
        id: tab_graph
        text: 'Graph'
        CMplGraph:
